export const LOGO_URL = '/logo.png'

export const formats = {
  format1: {
    id: 'format1',
    name: 'Footer Stripe',
    overlayUrl: '/footer-stripe.png',
    aspectRatio: 4 / 5,
    width: 1080,
    height: 1350,
  },
  format2: {
    id: 'format2',
    name: 'Logo + Number',
    overlayUrl: '/logo-number.png',
    aspectRatio: 4 / 5,
    width: 1080,
    height: 1350,
  },
  format3: {
    id: 'format3',
    name: 'Side Stripes',
    overlayUrl: '/side-stripes.png',
    aspectRatio: 4 / 5,
    width: 1080,
    height: 1350,
  },
  format4: {
    id: 'format4',
    name: 'With Lock',
    overlayUrl: '/with-lock.png',
    aspectRatio: 4 / 5,
    width: 1080,
    height: 1350,
  },
  format5: {
    id: 'format5',
    name: 'Product Overlay',
    overlayUrl: '/product-overlay.png',
    aspectRatio: 4 / 5,
    width: 1080,
    height: 1350,
  },
}

export const selectCards = [
  {
    id: 'format1',
    icon: 'fa-window-minimize',
    iconColor: 'text-purple-400',
    title: 'Footer Stripe',
    sub: 'Clean Footer',
    bg: '/footer-stripe.png',
    delay: 'delay-100',
  },
  {
    id: 'format2',
    icon: 'fa-address-card',
    iconColor: 'text-white',
    title: 'Logo + Number',
    sub: 'Contact Header',
    bg: '/logo-number.png',
    delay: 'delay-200',
  },
  {
    id: 'format3',
    icon: 'fa-grip-lines-vertical',
    iconColor: 'text-purple-300',
    title: 'Side Stripes',
    sub: 'Edgy Look',
    bg: '/side-stripes.png',
    delay: 'delay-300',
  },
  {
    id: 'format4',
    icon: 'fa-lock',
    iconColor: 'text-orange-400',
    title: 'With Lock',
    sub: 'Product Focus',
    bg: '/with-lock.png',
    delay: 'delay-400',
  },
  {
    id: 'format5',
    icon: 'fa-tags',
    iconColor: 'text-yellow-300',
    title: 'Product Overlay',
    sub: 'Bold Product Frame',
    bg: '/product-overlay.png',
    delay: 'delay-500',
  },
]

export const cardThemes = {
  tenacity: {
    name: 'Tenacity Core',
    icon: 'fa-lock',
    grad: ['#5e0060', '#b92b6a'],
    border: 'rgba(255,255,255,0.7)',
    borderStroke: 'rgba(255,255,255,0.9)',
    borderGlow: 'rgba(223,151,41,0.6)',
    text: '#ffffff',
    textShadow: '0 2px 6px rgba(0,0,0,0.5)',
    textShadowColor: 'rgba(0,0,0,0.5)',
    btn: ['#b92b6a', '#df9729'],
    btnText: '#ffffff',
    arrow: '#ffffff',
    cardShadow: '0 8px 24px rgba(94,0,96,0.3)',
  },
  gold: {
    name: 'Brass & Gold',
    icon: 'fa-key',
    grad: ['#1a1a1a', '#0a0a0a'],
    border: 'rgba(223,151,41,0.7)',
    borderStroke: 'rgba(223,151,41,0.9)',
    borderGlow: 'rgba(223,151,41,0.5)',
    text: '#df9729',
    textShadow: '0 2px 8px rgba(0,0,0,0.8)',
    textShadowColor: 'rgba(0,0,0,0.8)',
    btn: ['#df9729', '#f0b83b'],
    btnText: '#1a1a1a',
    arrow: '#df9729',
    cardShadow: '0 8px 24px rgba(223,151,41,0.2)',
  },
  dark: {
    name: 'Dark Slate',
    icon: 'fa-moon',
    grad: ['#2d2d2d', '#111111'],
    border: 'rgba(185,43,106,0.5)',
    borderStroke: 'rgba(185,43,106,0.8)',
    borderGlow: 'rgba(185,43,106,0.6)',
    text: '#ffffff',
    textShadow: '0 2px 8px rgba(0,0,0,0.8)',
    textShadowColor: 'rgba(0,0,0,0.8)',
    btn: ['#111111', '#2d2d2d'],
    btnText: '#b92b6a',
    arrow: '#b92b6a',
    cardShadow: '0 8px 24px rgba(0,0,0,0.4)',
  },
}

export const socials = [
  {
    href: 'https://wa.me/254711776688',
    icon: 'fa-whatsapp',
    brand: 'fa-brands',
    hover: 'hover:bg-[#25D366] hover:border-transparent',
  },
  {
    href: 'https://instagram.com/tenacitylocks',
    icon: 'fa-instagram',
    brand: 'fa-brands',
    hover:
      'hover:bg-gradient-to-tr hover:from-yellow-400 hover:via-pink-500 hover:to-purple-500 hover:border-transparent',
  },
  {
    href: 'https://facebook.com/tenacitylocks',
    icon: 'fa-facebook-f',
    brand: 'fa-brands',
    hover: 'hover:bg-[#1877F2] hover:border-transparent',
  },
]
